model Soltermica.Acumuladores.Interacumuladores.Ejemplos.Verificacion_04
parameter Real prescribedVolumeFlow_1.medium.rho(unit = "kg/m3", min = 0.0) 
  "density";
parameter Real prescribedVolumeFlow_1.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real prescribedVolumeFlow_1.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real prescribedVolumeFlow_1.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real prescribedVolumeFlow_1.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real prescribedVolumeFlow_1.m(unit = "kg", min = 0.0) = 0.1 
  "mass of medium";
parameter Real prescribedVolumeFlow_1.T0(unit = "K", min = 0.0) = 273.15 
  "initial temperature of medium";
parameter Real prescribedVolumeFlow_1.flowPort_a.medium.rho(unit = "kg/m3", 
  min = 0.0) "density";
parameter Real prescribedVolumeFlow_1.flowPort_a.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real prescribedVolumeFlow_1.flowPort_a.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real prescribedVolumeFlow_1.flowPort_a.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real prescribedVolumeFlow_1.flowPort_a.medium.nue(unit = "m2/s", 
  min = 0.0) "kinematic viscosity";
parameter Real prescribedVolumeFlow_1.flowPort_b.medium.rho(unit = "kg/m3", 
  min = 0.0) "density";
parameter Real prescribedVolumeFlow_1.flowPort_b.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real prescribedVolumeFlow_1.flowPort_b.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real prescribedVolumeFlow_1.flowPort_b.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real prescribedVolumeFlow_1.flowPort_b.medium.nue(unit = "m2/s", 
  min = 0.0) "kinematic viscosity";
parameter Real red.medium.rho(unit = "kg/m3", min = 0.0) "density";
parameter Real red.medium.cp(unit = "J/(kg.K)") "specific heat capacity at constant pressure";
parameter Real red.medium.cv(unit = "J/(kg.K)") "specific heat capacity at constant volume";
parameter Real red.medium.lamda(unit = "W/(m.K)") "thermal conductivity";
parameter Real red.medium.nue(unit = "m2/s", min = 0.0) "kinematic viscosity";
parameter Real red.flowPort.medium.rho(unit = "kg/m3", min = 0.0) "density";
parameter Real red.flowPort.medium.cp(unit = "J/(kg.K)") "specific heat capacity at constant pressure";
parameter Real red.flowPort.medium.cv(unit = "J/(kg.K)") "specific heat capacity at constant volume";
parameter Real red.flowPort.medium.lamda(unit = "W/(m.K)") "thermal conductivity";
parameter Real red.flowPort.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real red.p_Ambient(unit = "Pa") = 101300;
parameter Real red.T_Ambient(unit = "K", min = 0.0) = 273.15;
parameter Real caudal_1.k = 1E-006 "Constant output value";
parameter Real ambiente_b_1.medium.rho(unit = "kg/m3", min = 0.0) "density";
parameter Real ambiente_b_1.medium.cp(unit = "J/(kg.K)") "specific heat capacity at constant pressure";
parameter Real ambiente_b_1.medium.cv(unit = "J/(kg.K)") "specific heat capacity at constant volume";
parameter Real ambiente_b_1.medium.lamda(unit = "W/(m.K)") "thermal conductivity";
parameter Real ambiente_b_1.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real ambiente_b_1.flowPort.medium.rho(unit = "kg/m3", min = 0.0) 
  "density";
parameter Real ambiente_b_1.flowPort.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real ambiente_b_1.flowPort.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real ambiente_b_1.flowPort.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real ambiente_b_1.flowPort.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real ambiente_b_1.p_Ambient(unit = "Pa") = 101300;
parameter Real ambiente_b_1.T_Ambient(unit = "K", min = 0.0) = 273.15;
parameter Real consumo.medium.rho(unit = "kg/m3", min = 0.0) "density";
parameter Real consumo.medium.cp(unit = "J/(kg.K)") "specific heat capacity at constant pressure";
parameter Real consumo.medium.cv(unit = "J/(kg.K)") "specific heat capacity at constant volume";
parameter Real consumo.medium.lamda(unit = "W/(m.K)") "thermal conductivity";
parameter Real consumo.medium.nue(unit = "m2/s", min = 0.0) "kinematic viscosity";
parameter Real consumo.flowPort.medium.rho(unit = "kg/m3", min = 0.0) "density";
parameter Real consumo.flowPort.medium.cp(unit = "J/(kg.K)") "specific heat capacity at constant pressure";
parameter Real consumo.flowPort.medium.cv(unit = "J/(kg.K)") "specific heat capacity at constant volume";
parameter Real consumo.flowPort.medium.lamda(unit = "W/(m.K)") "thermal conductivity";
parameter Real consumo.flowPort.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real consumo.p_Ambient(unit = "Pa") = 101300;
parameter Real consumo.T_Ambient(unit = "K", min = 0.0) = 273.15;
parameter Real ambiente_a_1.medium.rho(unit = "kg/m3", min = 0.0) "density";
parameter Real ambiente_a_1.medium.cp(unit = "J/(kg.K)") "specific heat capacity at constant pressure";
parameter Real ambiente_a_1.medium.cv(unit = "J/(kg.K)") "specific heat capacity at constant volume";
parameter Real ambiente_a_1.medium.lamda(unit = "W/(m.K)") "thermal conductivity";
parameter Real ambiente_a_1.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real ambiente_a_1.flowPort.medium.rho(unit = "kg/m3", min = 0.0) 
  "density";
parameter Real ambiente_a_1.flowPort.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real ambiente_a_1.flowPort.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real ambiente_a_1.flowPort.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real ambiente_a_1.flowPort.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real TdistTemp.amplitude = 0 "Amplitude of trapezoid";
parameter Real TdistTemp.rising(unit = "s", min = 0.0) = 90 "Rising duration of trapezoid";
parameter Real TdistTemp.width(unit = "s", min = 0.0) = 200 "Width duration of trapezoid";
parameter Real TdistTemp.falling(unit = "s", min = 0.0) = 90 "Falling duration of trapezoid";
parameter Real TdistTemp.period(unit = "s", min = 1E-060) = 400 "Time for one period";
parameter Integer TdistTemp.nperiod = (-1) "Number of periods (< 0 means infinite number of periods)";
parameter Real TdistTemp.offset = 343.15 "Offset of output signal";
parameter Real TdistTemp.startTime(unit = "s") = 10 "Output = offset for time < startTime";
protected 
parameter Real TdistTemp.T_rising(unit = "s") = TdistTemp.rising 
  "End time of rising phase within one period";
parameter Real TdistTemp.T_width(unit = "s") = TdistTemp.T_rising+
  TdistTemp.width "End time of width phase within one period";
parameter Real TdistTemp.T_falling(unit = "s") = TdistTemp.T_width+
  TdistTemp.falling "End time of falling phase within one period";
public 
parameter Real Pconst_1.k = 101300 "Constant output value";
parameter Real interacumulador_01_1.flowPort_a_dep.medium.rho(unit = "kg/m3", 
  min = 0.0) "density";
parameter Real interacumulador_01_1.flowPort_a_dep.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real interacumulador_01_1.flowPort_a_dep.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real interacumulador_01_1.flowPort_a_dep.medium.lamda(unit = "W/(m.K)")
   "thermal conductivity";
parameter Real interacumulador_01_1.flowPort_a_dep.medium.nue(unit = "m2/s", 
  min = 0.0) "kinematic viscosity";
parameter Real interacumulador_01_1.flowPort_b_dep.medium.rho(unit = "kg/m3", 
  min = 0.0) "density";
parameter Real interacumulador_01_1.flowPort_b_dep.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real interacumulador_01_1.flowPort_b_dep.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real interacumulador_01_1.flowPort_b_dep.medium.lamda(unit = "W/(m.K)")
   "thermal conductivity";
parameter Real interacumulador_01_1.flowPort_b_dep.medium.nue(unit = "m2/s", 
  min = 0.0) "kinematic viscosity";
parameter Real interacumulador_01_1.medium_int.rho(unit = "kg/m3", min = 0.0) 
  "density";
parameter Real interacumulador_01_1.medium_int.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real interacumulador_01_1.medium_int.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real interacumulador_01_1.medium_int.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real interacumulador_01_1.medium_int.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real interacumulador_01_1.medium_dep.rho(unit = "kg/m3", min = 0.0) 
  "density";
parameter Real interacumulador_01_1.medium_dep.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real interacumulador_01_1.medium_dep.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real interacumulador_01_1.medium_dep.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real interacumulador_01_1.medium_dep.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real interacumulador_01_1.esp.V_dep(unit = "m3");
parameter Real interacumulador_01_1.esp.V_int(unit = "m3");
parameter Real interacumulador_01_1.esp.m_flow_int_nom(unit = "kg/s");
parameter Real interacumulador_01_1.esp.dp_int_nom(unit = "Pa");
parameter Real interacumulador_01_1.esp.m_flow_dep_nom(unit = "kg/s");
parameter Real interacumulador_01_1.esp.dp_dep_nom(unit = "Pa");
parameter Real interacumulador_01_1.esp.A_int(unit = "m2");
parameter Real interacumulador_01_1.esp.U_int;
parameter Real interacumulador_01_1.T0(unit = "K", min = 0.0) = 273.15;
parameter Real interacumulador_01_1.flowPort_a_int.medium.rho(unit = "kg/m3", 
  min = 0.0) "density";
parameter Real interacumulador_01_1.flowPort_a_int.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real interacumulador_01_1.flowPort_a_int.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real interacumulador_01_1.flowPort_a_int.medium.lamda(unit = "W/(m.K)")
   "thermal conductivity";
parameter Real interacumulador_01_1.flowPort_a_int.medium.nue(unit = "m2/s", 
  min = 0.0) "kinematic viscosity";
parameter Real interacumulador_01_1.flowPort_b_int.medium.rho(unit = "kg/m3", 
  min = 0.0) "density";
parameter Real interacumulador_01_1.flowPort_b_int.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real interacumulador_01_1.flowPort_b_int.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real interacumulador_01_1.flowPort_b_int.medium.lamda(unit = "W/(m.K)")
   "thermal conductivity";
parameter Real interacumulador_01_1.flowPort_b_int.medium.nue(unit = "m2/s", 
  min = 0.0) "kinematic viscosity";
parameter Real trapezoid.amplitude = 0.0003 "Amplitude of trapezoid";
parameter Real trapezoid.rising(unit = "s", min = 0.0) = 2 "Rising duration of trapezoid";
parameter Real trapezoid.width(unit = "s", min = 0.0) = 180 "Width duration of trapezoid";
parameter Real trapezoid.falling(unit = "s", min = 0.0) = 2 "Falling duration of trapezoid";
parameter Real trapezoid.period(unit = "s", min = 1E-060) = 3600 
  "Time for one period";
parameter Integer trapezoid.nperiod = (-1) "Number of periods (< 0 means infinite number of periods)";
parameter Real trapezoid.offset = 1E-006 "Offset of output signal";
parameter Real trapezoid.startTime(unit = "s") = 180 "Output = offset for time < startTime";
protected 
parameter Real trapezoid.T_rising(unit = "s") = trapezoid.rising 
  "End time of rising phase within one period";
parameter Real trapezoid.T_width(unit = "s") = trapezoid.T_rising+
  trapezoid.width "End time of width phase within one period";
parameter Real trapezoid.T_falling(unit = "s") = trapezoid.T_width+
  trapezoid.falling "End time of falling phase within one period";
public 
parameter Real prescribedVolumeFlow.medium.rho(unit = "kg/m3", min = 0.0) 
  "density";
parameter Real prescribedVolumeFlow.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real prescribedVolumeFlow.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real prescribedVolumeFlow.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real prescribedVolumeFlow.medium.nue(unit = "m2/s", min = 0.0) 
  "kinematic viscosity";
parameter Real prescribedVolumeFlow.m(unit = "kg", min = 0.0) = 0.1 
  "mass of medium";
parameter Real prescribedVolumeFlow.T0(unit = "K", min = 0.0) = 273.15 
  "initial temperature of medium";
parameter Real prescribedVolumeFlow.flowPort_a.medium.rho(unit = "kg/m3", min = 
  0.0) "density";
parameter Real prescribedVolumeFlow.flowPort_a.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real prescribedVolumeFlow.flowPort_a.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real prescribedVolumeFlow.flowPort_a.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real prescribedVolumeFlow.flowPort_a.medium.nue(unit = "m2/s", min = 
  0.0) "kinematic viscosity";
parameter Real prescribedVolumeFlow.flowPort_b.medium.rho(unit = "kg/m3", min = 
  0.0) "density";
parameter Real prescribedVolumeFlow.flowPort_b.medium.cp(unit = "J/(kg.K)") 
  "specific heat capacity at constant pressure";
parameter Real prescribedVolumeFlow.flowPort_b.medium.cv(unit = "J/(kg.K)") 
  "specific heat capacity at constant volume";
parameter Real prescribedVolumeFlow.flowPort_b.medium.lamda(unit = "W/(m.K)") 
  "thermal conductivity";
parameter Real prescribedVolumeFlow.flowPort_b.medium.nue(unit = "m2/s", min = 
  0.0) "kinematic viscosity";

Real prescribedVolumeFlow_1.dp(unit = "Pa") = prescribedVolumeFlow_1.flowPort_a.p
  -prescribedVolumeFlow_1.flowPort_b.p "pressure drop a->b";
Real prescribedVolumeFlow_1.V_flow(unit = "m3/s") = prescribedVolumeFlow_1.flowPort_a.m_flow
  /prescribedVolumeFlow_1.medium.rho "Volume flow a->b";
Real prescribedVolumeFlow_1.Q_flow(unit = "W") "heat exchange with ambient";
Real prescribedVolumeFlow_1.T(start = prescribedVolumeFlow_1.T0, unit = "K", 
  min = 0.0) "outlet temperature of medium";
Real prescribedVolumeFlow_1.T_a(unit = "K", min = 0.0) = prescribedVolumeFlow_1.flowPort_a.h
  /prescribedVolumeFlow_1.medium.cp "temperature at flowPort_a";
Real prescribedVolumeFlow_1.T_b(unit = "K", min = 0.0) = prescribedVolumeFlow_1.flowPort_b.h
  /prescribedVolumeFlow_1.medium.cp "temperature at flowPort_b";
Real prescribedVolumeFlow_1.dT(unit = "K") = (if noEvent(prescribedVolumeFlow_1.V_flow
   >= 0) then prescribedVolumeFlow_1.T-prescribedVolumeFlow_1.T_a else 
  prescribedVolumeFlow_1.T_b-prescribedVolumeFlow_1.T) "temperature increase of coolant in flow direction";
protected 
Real prescribedVolumeFlow_1.h(unit = "J/kg") = prescribedVolumeFlow_1.medium.cp*
  prescribedVolumeFlow_1.T "medium's specific enthalpy";
Real prescribedVolumeFlow_1.T_q(unit = "K", min = 0.0) = prescribedVolumeFlow_1.T
   "temperature relevant for heat exchange with ambient";
public 
Real prescribedVolumeFlow_1.flowPort_a.p(unit = "Pa");
Real prescribedVolumeFlow_1.flowPort_a.m_flow(unit = "kg/s");
Real prescribedVolumeFlow_1.flowPort_a.h(unit = "J/kg");
Real prescribedVolumeFlow_1.flowPort_a.H_flow(unit = "W");
Real prescribedVolumeFlow_1.flowPort_b.p(unit = "Pa");
Real prescribedVolumeFlow_1.flowPort_b.m_flow(unit = "kg/s");
Real prescribedVolumeFlow_1.flowPort_b.h(unit = "J/kg");
Real prescribedVolumeFlow_1.flowPort_b.H_flow(unit = "W");
Real prescribedVolumeFlow_1.VolumeFlow(unit = "m3/s");
Real red.T(unit = "K", min = 0.0) "outlet temperature of medium";
Real red.T_port(unit = "K", min = 0.0) = red.flowPort.h/red.medium.cp 
  "temperature at flowPort_a";
protected 
Real red.h(unit = "J/kg") = red.medium.cp*red.T;
public 
Real red.flowPort.p(unit = "Pa");
Real red.flowPort.m_flow(unit = "kg/s");
Real red.flowPort.h(unit = "J/kg");
Real red.flowPort.H_flow(unit = "W");
Real caudal_1.y "Connector of Real output signal";
Real ambiente_b_1.T(unit = "K", min = 0.0) "outlet temperature of medium";
Real ambiente_b_1.T_port(unit = "K", min = 0.0) = ambiente_b_1.flowPort.h/
  ambiente_b_1.medium.cp "temperature at flowPort_a";
protected 
Real ambiente_b_1.h(unit = "J/kg") = ambiente_b_1.medium.cp*ambiente_b_1.T;
public 
Real ambiente_b_1.flowPort.p(unit = "Pa");
Real ambiente_b_1.flowPort.m_flow(unit = "kg/s");
Real ambiente_b_1.flowPort.h(unit = "J/kg");
Real ambiente_b_1.flowPort.H_flow(unit = "W");
Real consumo.T(unit = "K", min = 0.0) "outlet temperature of medium";
Real consumo.T_port(unit = "K", min = 0.0) = consumo.flowPort.h/consumo.medium.cp
   "temperature at flowPort_a";
protected 
Real consumo.h(unit = "J/kg") = consumo.medium.cp*consumo.T;
public 
Real consumo.flowPort.p(unit = "Pa");
Real consumo.flowPort.m_flow(unit = "kg/s");
Real consumo.flowPort.h(unit = "J/kg");
Real consumo.flowPort.H_flow(unit = "W");
Real ambiente_a_1.T(unit = "K", min = 0.0) "outlet temperature of medium";
Real ambiente_a_1.T_port(unit = "K", min = 0.0) = ambiente_a_1.flowPort.h/
  ambiente_a_1.medium.cp "temperature at flowPort_a";
protected 
Real ambiente_a_1.h(unit = "J/kg") = ambiente_a_1.medium.cp*ambiente_a_1.T;
public 
Real ambiente_a_1.flowPort.p(unit = "Pa");
Real ambiente_a_1.flowPort.m_flow(unit = "kg/s");
Real ambiente_a_1.flowPort.h(unit = "J/kg");
Real ambiente_a_1.flowPort.H_flow(unit = "W");
Real ambiente_a_1.p_Ambient(unit = "Pa");
Real ambiente_a_1.T_Ambient(unit = "K", min = 0.0);
Real TdistTemp.y "Connector of Real output signal";
protected 
Real TdistTemp.T0(start = TdistTemp.startTime, unit = "s") "Start time of current period";
Integer TdistTemp.counter(start = TdistTemp.nperiod) "Period counter";
Integer TdistTemp.counter2(start = TdistTemp.nperiod);
public 
Real Pconst_1.y "Connector of Real output signal";
Real interacumulador_01_1.flowPort_a_dep.p(unit = "Pa");
Real interacumulador_01_1.flowPort_a_dep.m_flow(unit = "kg/s");
Real interacumulador_01_1.flowPort_a_dep.h(unit = "J/kg");
Real interacumulador_01_1.flowPort_a_dep.H_flow(unit = "W");
Real interacumulador_01_1.flowPort_b_dep.p(unit = "Pa");
Real interacumulador_01_1.flowPort_b_dep.m_flow(unit = "kg/s");
Real interacumulador_01_1.flowPort_b_dep.h(unit = "J/kg");
Real interacumulador_01_1.flowPort_b_dep.H_flow(unit = "W");
Real interacumulador_01_1.H_dep(unit = "J");
Real interacumulador_01_1.T_dep(unit = "K", min = 0.0);
Real interacumulador_01_1.T_in_AF(unit = "K", min = 0.0);
Real interacumulador_01_1.T_out_ACS(unit = "K", min = 0.0);
Real interacumulador_01_1.Q_int_dep(unit = "W");
Real interacumulador_01_1.H_int(unit = "J");
Real interacumulador_01_1.T_int(unit = "K", min = 0.0);
Real interacumulador_01_1.T_in_int(unit = "K", min = 0.0);
Real interacumulador_01_1.T_out_int(unit = "K", min = 0.0);
Real interacumulador_01_1.Q_int_int(unit = "W");
Real interacumulador_01_1.DeltaT(unit = "K");
Real interacumulador_01_1.flowPort_a_int.p(unit = "Pa");
Real interacumulador_01_1.flowPort_a_int.m_flow(unit = "kg/s");
Real interacumulador_01_1.flowPort_a_int.h(unit = "J/kg");
Real interacumulador_01_1.flowPort_a_int.H_flow(unit = "W");
Real interacumulador_01_1.flowPort_b_int.p(unit = "Pa");
Real interacumulador_01_1.flowPort_b_int.m_flow(unit = "kg/s");
Real interacumulador_01_1.flowPort_b_int.h(unit = "J/kg");
Real interacumulador_01_1.flowPort_b_int.H_flow(unit = "W");
Real trapezoid.y "Connector of Real output signal";
protected 
Real trapezoid.T0(start = trapezoid.startTime, unit = "s") "Start time of current period";
Integer trapezoid.counter(start = trapezoid.nperiod) "Period counter";
Integer trapezoid.counter2(start = trapezoid.nperiod);
public 
Real prescribedVolumeFlow.dp(unit = "Pa") = prescribedVolumeFlow.flowPort_a.p-
  prescribedVolumeFlow.flowPort_b.p "pressure drop a->b";
Real prescribedVolumeFlow.V_flow(unit = "m3/s") = prescribedVolumeFlow.flowPort_a.m_flow
  /prescribedVolumeFlow.medium.rho "Volume flow a->b";
Real prescribedVolumeFlow.Q_flow(unit = "W") "heat exchange with ambient";
Real prescribedVolumeFlow.T(start = prescribedVolumeFlow.T0, unit = "K", min = 
  0.0) "outlet temperature of medium";
Real prescribedVolumeFlow.T_a(unit = "K", min = 0.0) = prescribedVolumeFlow.flowPort_a.h
  /prescribedVolumeFlow.medium.cp "temperature at flowPort_a";
Real prescribedVolumeFlow.T_b(unit = "K", min = 0.0) = prescribedVolumeFlow.flowPort_b.h
  /prescribedVolumeFlow.medium.cp "temperature at flowPort_b";
Real prescribedVolumeFlow.dT(unit = "K") = (if noEvent(prescribedVolumeFlow.V_flow
   >= 0) then prescribedVolumeFlow.T-prescribedVolumeFlow.T_a else 
  prescribedVolumeFlow.T_b-prescribedVolumeFlow.T) "temperature increase of coolant in flow direction";
protected 
Real prescribedVolumeFlow.h(unit = "J/kg") = prescribedVolumeFlow.medium.cp*
  prescribedVolumeFlow.T "medium's specific enthalpy";
Real prescribedVolumeFlow.T_q(unit = "K", min = 0.0) = prescribedVolumeFlow.T 
  "temperature relevant for heat exchange with ambient";
public 
Real prescribedVolumeFlow.flowPort_a.p(unit = "Pa");
Real prescribedVolumeFlow.flowPort_a.m_flow(unit = "kg/s");
Real prescribedVolumeFlow.flowPort_a.h(unit = "J/kg");
Real prescribedVolumeFlow.flowPort_a.H_flow(unit = "W");
Real prescribedVolumeFlow.flowPort_b.p(unit = "Pa");
Real prescribedVolumeFlow.flowPort_b.m_flow(unit = "kg/s");
Real prescribedVolumeFlow.flowPort_b.h(unit = "J/kg");
Real prescribedVolumeFlow.flowPort_b.H_flow(unit = "W");
Real prescribedVolumeFlow.VolumeFlow(unit = "m3/s");

function Modelica.Thermal.FluidHeatFlow.Media.Water
  input Real rho := 995.6 "density";
  input Real cp := 4177 "specific heat capacity at constant pressure";
  input Real cv := 4177 "specific heat capacity at constant volume";
  input Real lamda := 0.615 "thermal conductivity";
  input Real nue := 8E-007 "kinematic viscosity";
  output Modelica.Thermal.FluidHeatFlow.Media.Water _out := Modelica.Thermal.FluidHeatFlow.Media.Water
    (
    rho = rho, 
    cp = cp, 
    cv = cv, 
    lamda = lamda, 
    nue = nue
  );

algorithm 
end Modelica.Thermal.FluidHeatFlow.Media.Water;
function Soltermica.Acumuladores.Interacumuladores.CatalogoEquipos.HEATSUN_ISSWX200
  input Real V_dep := 0.2;
  input Real V_int := 0.01;
  input Real m_flow_int_nom := 0.00055556;
  input Real dp_int_nom := 17800;
  input Real m_flow_dep_nom := 0.00055556;
  input Real dp_dep_nom := 17800;
  input Real A_int := 1;
  input Real U_int := 500;
  output Soltermica.Acumuladores.Interacumuladores.CatalogoEquipos.HEATSUN_ISSWX200 
    _out := Soltermica.Acumuladores.Interacumuladores.CatalogoEquipos.HEATSUN_ISSWX200
    (
    V_dep = V_dep, 
    V_int = V_int, 
    m_flow_int_nom = m_flow_int_nom, 
    dp_int_nom = dp_int_nom, 
    m_flow_dep_nom = m_flow_dep_nom, 
    dp_dep_nom = dp_dep_nom, 
    A_int = A_int, 
    U_int = U_int
  );

algorithm 
end Soltermica.Acumuladores.Interacumuladores.CatalogoEquipos.HEATSUN_ISSWX200;
equation
prescribedVolumeFlow_1.flowPort_a.m_flow+prescribedVolumeFlow_1.flowPort_b.m_flow
   = 0;
if (prescribedVolumeFlow_1.m > 1E-060) then 
  prescribedVolumeFlow_1.flowPort_a.H_flow+prescribedVolumeFlow_1.flowPort_b.H_flow
    +prescribedVolumeFlow_1.Q_flow = prescribedVolumeFlow_1.m*prescribedVolumeFlow_1.medium.cv
    *der(prescribedVolumeFlow_1.T);
else
  prescribedVolumeFlow_1.flowPort_a.H_flow+prescribedVolumeFlow_1.flowPort_b.H_flow
    +prescribedVolumeFlow_1.Q_flow = 0;
end if;
prescribedVolumeFlow_1.flowPort_a.H_flow = semiLinear(prescribedVolumeFlow_1.flowPort_a.m_flow,
   prescribedVolumeFlow_1.flowPort_a.h, prescribedVolumeFlow_1.h);
prescribedVolumeFlow_1.flowPort_b.H_flow = semiLinear(prescribedVolumeFlow_1.flowPort_b.m_flow,
   prescribedVolumeFlow_1.flowPort_b.h, prescribedVolumeFlow_1.h);
prescribedVolumeFlow_1.Q_flow = 0;
prescribedVolumeFlow_1.V_flow = prescribedVolumeFlow_1.VolumeFlow;
red.flowPort.H_flow = semiLinear(red.flowPort.m_flow, red.flowPort.h, red.h);
red.flowPort.p = red.p_Ambient;
red.T = red.T_Ambient;
caudal_1.y = caudal_1.k;
ambiente_b_1.flowPort.H_flow = semiLinear(ambiente_b_1.flowPort.m_flow, 
  ambiente_b_1.flowPort.h, ambiente_b_1.h);
ambiente_b_1.flowPort.p = ambiente_b_1.p_Ambient;
ambiente_b_1.T = ambiente_b_1.T_Ambient;
consumo.flowPort.H_flow = semiLinear(consumo.flowPort.m_flow, consumo.flowPort.h,
   consumo.h);
consumo.flowPort.p = consumo.p_Ambient;
consumo.T = consumo.T_Ambient;
ambiente_a_1.flowPort.H_flow = semiLinear(ambiente_a_1.flowPort.m_flow, 
  ambiente_a_1.flowPort.h, ambiente_a_1.h);
ambiente_a_1.flowPort.p = ambiente_a_1.p_Ambient;
ambiente_a_1.T = ambiente_a_1.T_Ambient;
when pre(TdistTemp.counter2) <> 0 and sample(TdistTemp.startTime, 
  TdistTemp.period) then
  TdistTemp.T0 = time;
  TdistTemp.counter2 = pre(TdistTemp.counter);
  TdistTemp.counter = pre(TdistTemp.counter)-(if pre(TdistTemp.counter) > 0
     then 1 else 0);
end when;
TdistTemp.y = TdistTemp.offset+(if time < TdistTemp.startTime or 
  TdistTemp.counter2 == 0 or time >= TdistTemp.T0+TdistTemp.T_falling then 0
   else (if time < TdistTemp.T0+TdistTemp.T_rising then (time-TdistTemp.T0)*
  TdistTemp.amplitude/TdistTemp.T_rising else (if time < TdistTemp.T0+
  TdistTemp.T_width then TdistTemp.amplitude else (TdistTemp.T0+TdistTemp.T_falling
  -time)*TdistTemp.amplitude/(TdistTemp.T_falling-TdistTemp.T_width))));
Pconst_1.y = Pconst_1.k;
interacumulador_01_1.T_in_AF = (if noEvent(interacumulador_01_1.flowPort_a_dep.m_flow
   > 0) then interacumulador_01_1.flowPort_a_dep.h/interacumulador_01_1.medium_dep.cp
   else interacumulador_01_1.T_dep);
interacumulador_01_1.T_out_ACS = interacumulador_01_1.T_dep;
interacumulador_01_1.T_in_int = (if noEvent(interacumulador_01_1.flowPort_a_int.m_flow
   > 0) then interacumulador_01_1.flowPort_a_int.h/interacumulador_01_1.medium_int.cp
   else interacumulador_01_1.T_int);
interacumulador_01_1.T_out_int = interacumulador_01_1.T_int;
interacumulador_01_1.flowPort_a_dep.p-interacumulador_01_1.flowPort_b_dep.p =  -
  interacumulador_01_1.esp.dp_dep_nom*interacumulador_01_1.flowPort_a_dep.m_flow
  ^2/interacumulador_01_1.esp.m_flow_dep_nom^2;
interacumulador_01_1.flowPort_a_int.p-interacumulador_01_1.flowPort_b_int.p =  -
  interacumulador_01_1.esp.dp_dep_nom*interacumulador_01_1.flowPort_a_int.m_flow
  ^2/interacumulador_01_1.esp.m_flow_dep_nom^2;
interacumulador_01_1.flowPort_a_dep.m_flow+interacumulador_01_1.flowPort_b_dep.m_flow
   = 0;
interacumulador_01_1.flowPort_a_int.m_flow+interacumulador_01_1.flowPort_b_int.m_flow
   = 0;
interacumulador_01_1.flowPort_a_dep.H_flow+interacumulador_01_1.flowPort_b_dep.H_flow
  +interacumulador_01_1.Q_int_dep = interacumulador_01_1.esp.V_dep*
  interacumulador_01_1.medium_dep.rho*interacumulador_01_1.medium_dep.cp*der(
  interacumulador_01_1.T_dep);
interacumulador_01_1.flowPort_a_int.H_flow+interacumulador_01_1.flowPort_b_int.H_flow
  +interacumulador_01_1.Q_int_int = interacumulador_01_1.esp.V_int*
  interacumulador_01_1.medium_int.rho*interacumulador_01_1.medium_int.cp*der(
  interacumulador_01_1.T_int);
interacumulador_01_1.Q_int_dep+interacumulador_01_1.Q_int_int = 0;
interacumulador_01_1.H_dep = interacumulador_01_1.esp.V_dep*interacumulador_01_1.medium_dep.rho
  *interacumulador_01_1.medium_dep.cp*interacumulador_01_1.T_dep;
interacumulador_01_1.H_int = interacumulador_01_1.esp.V_int*interacumulador_01_1.medium_int.rho
  *interacumulador_01_1.medium_int.cp*interacumulador_01_1.T_int;
interacumulador_01_1.flowPort_a_dep.H_flow = (if noEvent(interacumulador_01_1.flowPort_a_dep.m_flow
   > 0) then interacumulador_01_1.flowPort_a_dep.m_flow*interacumulador_01_1.medium_dep.cp
  *interacumulador_01_1.T_in_AF else 0);
interacumulador_01_1.flowPort_b_dep.H_flow = (if noEvent(interacumulador_01_1.flowPort_b_dep.m_flow
   < 0) then interacumulador_01_1.flowPort_b_dep.m_flow*interacumulador_01_1.medium_dep.cp
  *interacumulador_01_1.T_out_ACS else 0);
interacumulador_01_1.flowPort_a_int.H_flow = (if noEvent(interacumulador_01_1.flowPort_a_int.m_flow
   > 0) then interacumulador_01_1.flowPort_a_int.m_flow*interacumulador_01_1.medium_int.cp
  *interacumulador_01_1.T_in_int else 0);
interacumulador_01_1.flowPort_b_int.H_flow = (if noEvent(interacumulador_01_1.flowPort_b_int.m_flow
   < 0) then interacumulador_01_1.flowPort_b_int.m_flow*interacumulador_01_1.medium_int.cp
  *interacumulador_01_1.T_out_int else 0);
interacumulador_01_1.DeltaT = 0.5*(interacumulador_01_1.T_in_int+
  interacumulador_01_1.T_int)-interacumulador_01_1.T_dep;
interacumulador_01_1.Q_int_dep = interacumulador_01_1.esp.U_int*interacumulador_01_1.esp.A_int
  *interacumulador_01_1.DeltaT;
when pre(trapezoid.counter2) <> 0 and sample(trapezoid.startTime, 
  trapezoid.period) then
  trapezoid.T0 = time;
  trapezoid.counter2 = pre(trapezoid.counter);
  trapezoid.counter = pre(trapezoid.counter)-(if pre(trapezoid.counter) > 0
     then 1 else 0);
end when;
trapezoid.y = trapezoid.offset+(if time < trapezoid.startTime or 
  trapezoid.counter2 == 0 or time >= trapezoid.T0+trapezoid.T_falling then 0
   else (if time < trapezoid.T0+trapezoid.T_rising then (time-trapezoid.T0)*
  trapezoid.amplitude/trapezoid.T_rising else (if time < trapezoid.T0+
  trapezoid.T_width then trapezoid.amplitude else (trapezoid.T0+trapezoid.T_falling
  -time)*trapezoid.amplitude/(trapezoid.T_falling-trapezoid.T_width))));
prescribedVolumeFlow.flowPort_a.m_flow+prescribedVolumeFlow.flowPort_b.m_flow = 0;
if (prescribedVolumeFlow.m > 1E-060) then 
  prescribedVolumeFlow.flowPort_a.H_flow+prescribedVolumeFlow.flowPort_b.H_flow+
    prescribedVolumeFlow.Q_flow = prescribedVolumeFlow.m*prescribedVolumeFlow.medium.cv
    *der(prescribedVolumeFlow.T);
else
  prescribedVolumeFlow.flowPort_a.H_flow+prescribedVolumeFlow.flowPort_b.H_flow+
    prescribedVolumeFlow.Q_flow = 0;
end if;
prescribedVolumeFlow.flowPort_a.H_flow = semiLinear(prescribedVolumeFlow.flowPort_a.m_flow,
   prescribedVolumeFlow.flowPort_a.h, prescribedVolumeFlow.h);
prescribedVolumeFlow.flowPort_b.H_flow = semiLinear(prescribedVolumeFlow.flowPort_b.m_flow,
   prescribedVolumeFlow.flowPort_b.h, prescribedVolumeFlow.h);
prescribedVolumeFlow.Q_flow = 0;
prescribedVolumeFlow.V_flow = prescribedVolumeFlow.VolumeFlow;
ambiente_a_1.p_Ambient = Pconst_1.y;
ambiente_a_1.T_Ambient = TdistTemp.y;
ambiente_a_1.flowPort.H_flow+prescribedVolumeFlow_1.flowPort_a.H_flow = 0;
prescribedVolumeFlow_1.flowPort_a.h = ambiente_a_1.flowPort.h;
ambiente_a_1.flowPort.m_flow+prescribedVolumeFlow_1.flowPort_a.m_flow = 0;
assert(abs(prescribedVolumeFlow_1.flowPort_a.medium.cp-ambiente_a_1.flowPort.medium.cp)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_a.medium.cv-ambiente_a_1.flowPort.medium.cv)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_a.medium.lamda-ambiente_a_1.flowPort.medium.lamda)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_a.medium.nue-ambiente_a_1.flowPort.medium.nue)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_a.medium.rho-ambiente_a_1.flowPort.medium.rho)
   <= 0, "Parameters in connected connectors must be equal");
prescribedVolumeFlow_1.flowPort_a.p = ambiente_a_1.flowPort.p;
ambiente_b_1.flowPort.H_flow+interacumulador_01_1.flowPort_b_int.H_flow = 0;
interacumulador_01_1.flowPort_b_int.h = ambiente_b_1.flowPort.h;
ambiente_b_1.flowPort.m_flow+interacumulador_01_1.flowPort_b_int.m_flow = 0;
assert(abs(interacumulador_01_1.flowPort_b_int.medium.cp-ambiente_b_1.flowPort.medium.cp)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_int.medium.cv-ambiente_b_1.flowPort.medium.cv)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_int.medium.lamda-ambiente_b_1.flowPort.medium.lamda)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_int.medium.nue-ambiente_b_1.flowPort.medium.nue)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_int.medium.rho-ambiente_b_1.flowPort.medium.rho)
   <= 0, "Parameters in connected connectors must be equal");
interacumulador_01_1.flowPort_b_int.p = ambiente_b_1.flowPort.p;
prescribedVolumeFlow_1.VolumeFlow = caudal_1.y;
consumo.flowPort.H_flow+interacumulador_01_1.flowPort_b_dep.H_flow = 0;
interacumulador_01_1.flowPort_b_dep.h = consumo.flowPort.h;
consumo.flowPort.m_flow+interacumulador_01_1.flowPort_b_dep.m_flow = 0;
assert(abs(interacumulador_01_1.flowPort_b_dep.medium.cp-consumo.flowPort.medium.cp)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_dep.medium.cv-consumo.flowPort.medium.cv)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_dep.medium.lamda-consumo.flowPort.medium.lamda)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_dep.medium.nue-consumo.flowPort.medium.nue)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(interacumulador_01_1.flowPort_b_dep.medium.rho-consumo.flowPort.medium.rho)
   <= 0, "Parameters in connected connectors must be equal");
interacumulador_01_1.flowPort_b_dep.p = consumo.flowPort.p;
interacumulador_01_1.flowPort_a_dep.H_flow+prescribedVolumeFlow.flowPort_b.H_flow
   = 0;
prescribedVolumeFlow.flowPort_b.h = interacumulador_01_1.flowPort_a_dep.h;
interacumulador_01_1.flowPort_a_dep.m_flow+prescribedVolumeFlow.flowPort_b.m_flow
   = 0;
assert(abs(prescribedVolumeFlow.flowPort_b.medium.cp-interacumulador_01_1.flowPort_a_dep.medium.cp)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow.flowPort_b.medium.cv-interacumulador_01_1.flowPort_a_dep.medium.cv)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow.flowPort_b.medium.lamda-interacumulador_01_1.flowPort_a_dep.medium.lamda)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow.flowPort_b.medium.nue-interacumulador_01_1.flowPort_a_dep.medium.nue)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow.flowPort_b.medium.rho-interacumulador_01_1.flowPort_a_dep.medium.rho)
   <= 0, "Parameters in connected connectors must be equal");
prescribedVolumeFlow.flowPort_b.p = interacumulador_01_1.flowPort_a_dep.p;
interacumulador_01_1.flowPort_a_int.H_flow+prescribedVolumeFlow_1.flowPort_b.H_flow
   = 0;
prescribedVolumeFlow_1.flowPort_b.h = interacumulador_01_1.flowPort_a_int.h;
interacumulador_01_1.flowPort_a_int.m_flow+prescribedVolumeFlow_1.flowPort_b.m_flow
   = 0;
assert(abs(prescribedVolumeFlow_1.flowPort_b.medium.cp-interacumulador_01_1.flowPort_a_int.medium.cp)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_b.medium.cv-interacumulador_01_1.flowPort_a_int.medium.cv)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_b.medium.lamda-interacumulador_01_1.flowPort_a_int.medium.lamda)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_b.medium.nue-interacumulador_01_1.flowPort_a_int.medium.nue)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(prescribedVolumeFlow_1.flowPort_b.medium.rho-interacumulador_01_1.flowPort_a_int.medium.rho)
   <= 0, "Parameters in connected connectors must be equal");
prescribedVolumeFlow_1.flowPort_b.p = interacumulador_01_1.flowPort_a_int.p;
trapezoid.y = prescribedVolumeFlow.VolumeFlow;
prescribedVolumeFlow.flowPort_a.H_flow+red.flowPort.H_flow = 0;
red.flowPort.h = prescribedVolumeFlow.flowPort_a.h;
prescribedVolumeFlow.flowPort_a.m_flow+red.flowPort.m_flow = 0;
assert(abs(red.flowPort.medium.cp-prescribedVolumeFlow.flowPort_a.medium.cp) <= 0,
   "Parameters in connected connectors must be equal");
assert(abs(red.flowPort.medium.cv-prescribedVolumeFlow.flowPort_a.medium.cv) <= 0,
   "Parameters in connected connectors must be equal");
assert(abs(red.flowPort.medium.lamda-prescribedVolumeFlow.flowPort_a.medium.lamda)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(red.flowPort.medium.nue-prescribedVolumeFlow.flowPort_a.medium.nue)
   <= 0, "Parameters in connected connectors must be equal");
assert(abs(red.flowPort.medium.rho-prescribedVolumeFlow.flowPort_a.medium.rho)
   <= 0, "Parameters in connected connectors must be equal");
red.flowPort.p = prescribedVolumeFlow.flowPort_a.p;

initial equation
  interacumulador_01_1.T_int = interacumulador_01_1.T0;
  interacumulador_01_1.T_in_int = interacumulador_01_1.T_int;
  interacumulador_01_1.T_dep = interacumulador_01_1.T0;
  interacumulador_01_1.T_in_AF = interacumulador_01_1.T_dep;

end Soltermica.Acumuladores.Interacumuladores.Ejemplos.Verificacion_04;
DAE having 103 scalar unknowns and 103 scalar equations.
